---
- name: Install
  become : yes
  apt: 
    name: nginx 
    state: latest

- name: Start server
  become: yes
  service: 
    name: nginx
    state: started
    enabled: True

- name: supprimez default.conf
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: nginx reload

- name: config site
  include: site.yml
  with_items: "{{ domains }}"