---
- name: Installation de git
  apt: 
    name : git

- name: Installation de Vim
  apt: 
    name: vim

- name: Install "{{ package }}"
  when: package is defined
  apt:
    name: "{{ package }}"
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
